USE NW_LOJA

DECLARE @DATA_VENDA DATETIME, @CODIGO_FILIAL AS VARCHAR(10)
DECLARE @DATA_FIM DATETIME
SET @DATA_VENDA = '20161108'
SET @CODIGO_FILIAL = '019'
SET @DATA_FIM = '20161108'

IF (SELECT OBJECT_ID('LOJA_CF_SAT')) IS NULL  
      
      BEGIN
      
            SELECT 'LOJA_VENDA' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA
            WHERE DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_PARCELAS' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_PARCELAS A JOIN LOJA_VENDA B ON A.TERMINAL = B.TERMINAL
            AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_PGTO' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_PGTO A JOIN LOJA_VENDA B ON A.TERMINAL = B.TERMINAL
            AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_PRODUTO' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_PRODUTO A JOIN LOJA_VENDA B ON A.TICKET = B.TICKET
            AND A.DATA_VENDA = B.DATA_VENDA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_TROCA' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_TROCA A JOIN LOJA_VENDA B ON A.TICKET = B.TICKET
            AND A.DATA_VENDA = B.DATA_VENDA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_VENDEDORES' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_VENDEDORES A JOIN LOJA_VENDA B ON A.TICKET = B.TICKET
            AND A.DATA_VENDA = B.DATA_VENDA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CONTROLE_FISCAL' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_CONTROLE_FISCAL
            WHERE DATA_FISCAL BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CONTROLE_AJUSTE' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_CONTROLE_AJUSTE
            WHERE DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_ENTRADAS' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_ENTRADAS A
            JOIN FILIAIS B ON A.FILIAL = B.FILIAL
            WHERE EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CLIFOR = @CODIGO_FILIAL
            AND ENTRADA_CONFERIDA = 1
            UNION ALL
            SELECT 'LOJA_SAIDAS' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_SAIDAS A
            JOIN FILIAIS B ON A.FILIAL = B.FILIAL
            WHERE EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CLIFOR = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_NOTA_FISCAL' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_NOTA_FISCAL
            WHERE EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_NOTA_FISCAL_ITEM' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_NOTA_FISCAL_ITEM A
            JOIN LOJA_NOTA_FISCAL B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL
            AND A.NF_NUMERO = B.NF_NUMERO
            AND A.SERIE_NF = B.SERIE_NF
            WHERE B.EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_NOTA_FISCAL_IMPOSTO' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_NOTA_FISCAL_IMPOSTO A
            JOIN LOJA_NOTA_FISCAL B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL
            AND A.NF_NUMERO = B.NF_NUMERO
            AND A.SERIE_NF = B.SERIE_NF
            WHERE B.EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'U_LOJA_VENDA_PRODUTO_DESCONTO' AS TABELA, COUNT(*)AS QTDE
            FROM U_LOJA_VENDA_PRODUTO_DESCONTO A
            WHERE A.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND a.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CAIXA_LANCAMENTOS' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_CAIXA_LANCAMENTOS
            WHERE DATA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CONTROLE_FISCAL_TARIFAS' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_CONTROLE_FISCAL_TARIFAS
            WHERE DATA_FISCAL BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
             
      END

ELSE

      BEGIN

            SELECT 'LOJA_VENDA' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA
            WHERE DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_PARCELAS' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_PARCELAS A JOIN LOJA_VENDA B ON A.TERMINAL = B.TERMINAL
            AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_PGTO' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_PGTO A JOIN LOJA_VENDA B ON A.TERMINAL = B.TERMINAL
            AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_PRODUTO' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_PRODUTO A JOIN LOJA_VENDA B ON A.TICKET = B.TICKET
            AND A.DATA_VENDA = B.DATA_VENDA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_TROCA' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_TROCA A JOIN LOJA_VENDA B ON A.TICKET = B.TICKET
            AND A.DATA_VENDA = B.DATA_VENDA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_VENDA_VENDEDORES' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_VENDA_VENDEDORES A JOIN LOJA_VENDA B ON A.TICKET = B.TICKET
            AND A.DATA_VENDA = B.DATA_VENDA
            AND A.CODIGO_FILIAL = B.CODIGO_FILIAL
            WHERE B.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CONTROLE_FISCAL' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_CONTROLE_FISCAL
            WHERE DATA_FISCAL BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CONTROLE_AJUSTE' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_CONTROLE_AJUSTE
            WHERE DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_ENTRADAS' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_ENTRADAS A
            JOIN FILIAIS B ON A.FILIAL = B.FILIAL
            WHERE EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CLIFOR = @CODIGO_FILIAL
            AND ENTRADA_CONFERIDA = 1
            UNION ALL
            SELECT 'LOJA_SAIDAS' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_SAIDAS A
            JOIN FILIAIS B ON A.FILIAL = B.FILIAL
            WHERE EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CLIFOR = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_NOTA_FISCAL' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_NOTA_FISCAL
            WHERE EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_NOTA_FISCAL_ITEM' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_NOTA_FISCAL_ITEM A
            JOIN LOJA_NOTA_FISCAL B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL
            AND A.NF_NUMERO = B.NF_NUMERO
            AND A.SERIE_NF = B.SERIE_NF
            WHERE B.EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_NOTA_FISCAL_IMPOSTO' AS TABELA, COUNT(*)AS QTDE
            FROM LOJA_NOTA_FISCAL_IMPOSTO A
            JOIN LOJA_NOTA_FISCAL B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL
            AND A.NF_NUMERO = B.NF_NUMERO
            AND A.SERIE_NF = B.SERIE_NF
            WHERE B.EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND B.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'U_LOJA_VENDA_PRODUTO_DESCONTO' AS TABELA, COUNT(*)AS QTDE
            FROM U_LOJA_VENDA_PRODUTO_DESCONTO A
            WHERE A.DATA_VENDA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND a.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CAIXA_LANCAMENTOS' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_CAIXA_LANCAMENTOS
            WHERE DATA BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CONTROLE_FISCAL_TARIFAS' AS TABELA, COUNT(*)AS QTDE 
            FROM LOJA_CONTROLE_FISCAL_TARIFAS
            WHERE DATA_FISCAL BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CF_SAT' AS TABELA, COUNT (*) AS QTDE
            FROM LOJA_CF_SAT
            WHERE EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CF_SAT_ITEM' AS TABELA, COUNT (*) AS QTDE
            FROM LOJA_CF_SAT_ITEM AS F
            JOIN LOJA_CF_SAT AS G
            ON F.ID_LOJA_CF_SAT = G.ID_LOJA_CF_SAT
            AND F.CODIGO_FILIAL = G.CODIGO_FILIAL
            WHERE G.EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND F.CODIGO_FILIAL = @CODIGO_FILIAL
            UNION ALL
            SELECT 'LOJA_CF_SAT_IMPOSTO' AS TABELA, COUNT (*) AS QTDE
            FROM LOJA_CF_SAT_IMPOSTO AS H
            JOIN LOJA_CF_SAT AS I
            ON H.ID_LOJA_CF_SAT = I.ID_LOJA_CF_SAT
            AND H.CODIGO_FILIAL = I.CODIGO_FILIAL
            WHERE I.EMISSAO BETWEEN @DATA_VENDA AND @DATA_FIM
            AND I.CODIGO_FILIAL = @CODIGO_FILIAL

      END
